### ISSUE TITLE
新版本似乎不支持cron了

### ISSUE THREAD

**Issue by behinder85** [Reseed-Puppy/Reseed-Puppy#11]
一使用cron就报错：
E500 - 服务器繁忙，请稍候再试！
![2023-12-03_122957](https://github.com/Reseed-Puppy/Reseed-Puppy/assets/60542924/df746e6c-f28a-45e2-af99-908efd622886)

**Comment by zxfsadly** [comment]
我来排查一下

**Comment by zxfsadly** [comment]
目前还未适配cron表达式，现在仅支持秒数
